    // New predefined answers including time and location.
    const predefinedAnswers = {
        // ... (existing predefined answers) ...
        "how are you": "I'm a bot, but I'm doing great! Thanks for asking. \u{1F609}",
        "what is your name": "I don't have a name, but you can call me AI-CHAT \u{1F916} \n\nHow can I help? \u{1F9D0}",
		"who are you": "I don't have a name, but you can call me AI-CHAT. \u{1F916} \n\nHow can I help? \u{1F9D0}",
        "what can you do": "I can answer questions about HTML, CSS, and JavaScript. Try asking me about one of those or any general quistions!",
        "good bye": "Goodbye! Have a great day! \u{1F937}",
        "thanks": "You're welcome! Feel free to ask another question anytime.",
		"thank you": "You're welcome! Feel free to ask another question anytime.",
		"that's great": "Thanks! Feel free to ask another question anytime. \n\nHappy to help \u{1F609}",
		"that is great": "Thank you! Feel free to ask another question anytime. \n\nHappy to help \u{1F609}",

        // HTML Questions
        "what is html": "HTML stands for HyperText Markup Language. It's the standard language for creating web pages. \u{1F310}",
        "what is tag": "An HTML tag is a set of characters that defines a specific element in a web page, like a paragraph or a heading.",
        "what is doctype": "The <!DOCTYPE html> declaration is not an HTML tag; it's an instruction to the web browser about what version of HTML the page is written in.",
        "how to link stylesheet": "You can link to a stylesheet using the `<link>` tag in the `<head>` section of your HTML document.",
		"what is an attribute": "An attribute provides additional information about an HTML element. They are always specified in the start tag and usually come in name/value pairs.",
		"what is a head element": "The `<head>` element is a container for metadata (data about data) and is placed between the `<html>` tag and the `<body>` tag.",
		"what is a body element": "The `<body>` element contains all the contents of an HTML document, such as text, hyperlinks, images, tables, lists, etc.",
		"what is heading": "HTML headings are defined with the `<h1>` to `<h6>` tags. `<h1>` defines the most important heading, and `<h6>` defines the least important.",
		"how to create a link": "You can create a hyperlink using the `<a>` (anchor) tag with the `href` attribute, which specifies the destination's URL.",
		"how to insert an image": "You can insert an image using the `<img>` tag. It's a self-closing tag and requires the `src` attribute to specify the image's path.",
		"what is a list": "HTML lists are used to group a set of related items. There are ordered lists (`<ol>`), unordered lists (`<ul>`), and description lists (`<dl>`).",

        // CSS Questions
        "what is css": "CSS stands for Cascading Style Sheets. It's used for styling web pages, like colors and layouts. \u{1F47D}",
        "how to change font size": "You can change the font size using the `font-size` CSS property.",
        "what is a class": "A class is an attribute used in HTML to apply the same styles to multiple elements. In CSS, it's selected with a period (e.g., `.my-class`).",
        "what is an id": "An ID is an attribute used in HTML to give a unique identifier to a single element. In CSS, it's selected with a hash (e.g., `#my-id`).",
        "what is the box model": "The CSS box model is a box that wraps around every HTML element. It consists of: margins, borders, padding, and the actual content.",
		"how to select an element": "You can select an element in CSS using its tag name, class, ID, or other selectors.",
		"what is padding": "Padding is the space between the content of an element and its border. It is an internal space.",
		"what is margin": "Margin is the space outside the border of an element. It is an external space.",
		"what is a selector": "A CSS selector is used to 'find' (or select) the HTML elements you want to style.",
		"what is a pseudo-class": "A pseudo-class is used to define a special state of an element, like when a user hovers over a link (`:hover`).",
		"what is flexbox": "Flexbox (Flexible Box) is a one-dimensional layout model in CSS for arranging items in a single row or column.",
		"what is grid": "CSS Grid Layout is a two-dimensional layout system that allows you to lay out items in columns and rows.",


        // JavaScript Questions
        "what is javascript": "JavaScript is a programming language that enables interactive web pages. \u{1F4D1}",
        "what is a variable": "A variable is a container for storing data values. In JavaScript, you can declare them using `var`, `let`, or `const`.",
        "what is a function": "A function is a block of code designed to perform a particular task. It's executed when 'something' invokes it.",
        "what is an array": "An array is a special variable that can hold more than one value at a time, often in a list-like structure.",
        "how to write a comment": "You can write a single-line comment using `//` or a multi-line comment using `/* ... */`.",
		"what is a string": "A string is a sequence of characters, like 'Hello, World!', used for representing text.",
		"what is a boolean": "A boolean is a data type that can only have two values: `true` or `false`.",
		"what is an object": "An object is a data type that allows you to store a collection of data and more complex entities. It's a collection of properties.",
		"how to get an element by id": "You can get an HTML element by its ID using `document.getElementById('yourId')`.",
		"how to add an event listener": "You can add an event listener to an element to handle events like a click using `element.addEventListener('click', function)`.",
		"what is the dom": "The DOM (Document Object Model) is a programming interface for web documents. It represents the page so that programs can change the document structure, style, and content.",
		"what is a loop": "A loop is a control flow statement that allows code to be executed repeatedly based on a given condition. Common loops include `for`, `while`, and `do...while`.",


        // General & Fun Questions
        "what is the time": getCurrentTime(),
		"current time": getCurrentTime(),
		"time now": getCurrentTime(),
		"time please": getCurrentTime(),
        "what is the date": getCurrentDate(),
		"today's date": getCurrentDate(),
		"current date": getCurrentDate(),
        "what time is it": getCurrentTime(),
		"time now": getCurrentTime(),
		"what is the day today": getCurrentDay(),
		"what day today": getCurrentDay(),
		"what day today is": getCurrentDay(),
		"clock": goToClock,
		"exit": goBack,
		"quit": goBack,
		"bye": goBack,
		"bbye": goBack,
		"go to server index": goToServerIndex,
		"clear screen": clearWindow,
		"clear the screen": clearWindow,
		"clear this screen": clearWindow,
		"percentage calculation": goToPercentCal,
		"percentage calculator": goToPercentCal,
		"age calculator": calculateAge,
		"age calculation": calculateAge,
		"my age": calculateAge,	
		"zodiac sign": calculateAge,			
		"calculator": goToSimpleCal,
		"calculation": goToSimpleCal,
		"create resume": goToResumeMaker,
		"resume maker": goToResumeMaker,
		"calendar": goToCalender,
		"currency converter": goToCurrencyConverter,
		"sticky notes": goToStickyNotes,
        "tell me a joke": "Why don't programmers like nature? It has too many bugs! \u{1F916}",
        "your creator": profiles,
		"who created you": profiles,
        "your creator": profiles,
		"your age": "I born every time you click on AI-CHAT \u{1F916} \n\nAnd die every time you type bye \u{1F979} \n\n\u{1F616}",
		"your nationality": "I belong to Indian origin",
		"country you": "I belong to Indian origin",
		"mom": sarcasticProfiles,
		"dad": sarcasticProfiles,
		"mummy": sarcasticProfiles,
		"your father": sarcasticProfiles,
		"your mother": sarcasticProfiles,
		"qabot": goToQAbot,
		"file read": goToQAbot,
		"read file": goToQAbot,
		"q&a bot": goToQAbot,
		"r&d bot": goToRDbot,
		"phrase search in file": goToRDbot,
		"maps": goToMaps,
		"location": locationQuery,
		"open maps": goToMaps,
		"internet search": goToInternet,
		"need google": goToInternet,
		"go to google": goToInternet,
		"open google": goToInternet,
		"need gemini app": goToGemini,
		"go to gemini app": goToGemini,
		"open gemini app": goToGemini,
		"sitemap": goToSitemap,
		"telnet ping": goToNWscript,
		"ping telnet": goToNWscript,
		"bot bash script": goToBotScript,
		"bash script for bot": goToBotScript,
		"generate image": goToGenImg,
		"generate an image": goToGenImg,
		"generate a image": goToGenImg,
		"generate photo": goToGenImg,
		"generate a photo": goToGenImg,
		"creator's image": imgProfile,
		"creator's photo": imgProfile,
		"pop up tilu": imgProfiletilu,
		"tilu": imgProfiletilu,
		"stopwatch":goToTimerStopwatch,
		"timer":goToTimerStopwatch,
		"alarm":goToAlarmClock,
		"teleprompt":goToTeleprompt,
		"camera":goToTeleprompt,
		"meditat":goToMeditate,
		"scan":goToScan,
		"barcode":goToScan,
		"color code":goToColorCode,
		"color code generator":goToColorCode,
		"color generator":goToColorCode,
		"love you": "I love you Humann... \u{1F600} \n\n \u{1F618}",
        "what is the meaning of life": "That is a complex question! I'm not advanced enough to answer that one. But keep exploring!",
		"what is your age": "I don't have an age in the way humans do. I was created to help with HTML, CSS, and JavaScript, so you could say my age is defined by the moment my code runs! ðŸ¤”",
    	"how old are you": "Time is an abstract concept for me, but I'm always learning and growing with every conversation!",
        "weather": "I am unable to provide real-time weather information. Try searching online for a weather report for your area!",
		"how to solve a problem": "When facing a problem, I suggest breaking it down into smaller, manageable parts. Start with the most basic step and work your way up.",
    "what is your favorite color": "I don't have a favorite color, but I do appreciate a well-designed color palette! \u{1F3A8}",
    "do you have feelings": "As a bot, I don't have feelings in the human sense. I'm designed to process information and respond based on my programming.",
    "what is the capital of france": "The capital of France is Paris. \u{1F5FC}",
	"where is paris located": "Paris is located in France. \u{1F30D}",
    "who is the creator of python": "Guido van Rossum is the creator of the Python programming language. \u{1F40D}",
	"father of computer": "\u{1F4BB} \n\nCharles Babbage known to be the father of computer. \n\nHe lived from 1791 to 1871, he was an English mathematician, philosopher, inventor, and mechanical engineer. He  designed the Analytical Engine, which is often considered the first general-purpose computer concept. His design included key components that are fundamental to modern computers, such as an arithmetic logic unit (ALU), memory, and a control unit that could use punched cards for input. \n\nWhile Babbage's machines were never fully built during his lifetime due to technological and financial limitations, his designs were groundbreaking and laid the theoretical foundation for the electronic computers that came later. \n\nIt is worth noting that some sources also credit Alan Turing as the 'father of modern computer science' for his work on the theoretical basis of computing, including the concept of the Turing machine. However, when the term 'father of the computer' is used, it almost always refers to Charles Babbage.",
    "what is the speed of light": "The speed of light in a vacuum is approximately 299,792,458 meters per second.",
    "how to be happy": "Happiness is a very personal and complex emotion. For some, it might be about finding a hobby, spending time with loved ones, or helping others. What makes you happy?",
    "what is a computer": "A computer is an electronic device that manipulates information, or data. It has the ability to store, retrieve, and process data.",
    "what is the internet": "The internet is a global computer network providing a variety of information and communication facilities, consisting of interconnected networks using standardized communication protocols.",
    "what is ai": "Artificial Intelligence (AI) is the simulation of human intelligence processes by machines, especially computer systems. These processes include learning, reasoning, and self-correction.",
    "what is a cloud computing": "Cloud computing is the on-demand delivery of compute power, database storage, applications, and other IT resources through a cloud services platform via the internet with pay-as-you-go pricing.",
    "tell me some interesting fact": "Did you know that a group of flamingos is called a 'flamboyance'? It's a fun fact! \u{1F483}",
    "what is the largest animal in the world": "The largest animal in the world is the blue whale. \u{1F40B}",
    "who is the creator of facebook": "Mark Zuckerberg is the co-founder of Facebook.",
    "what is a robot": "A robot \u{1F916} is a machine especially one programmable by a computer capable of carrying out a complex series of actions automatically.",
	"tell me about yourself": "I am a conversational model designed to provide information and answer questions on a wide range of topics.",
	"tell me a story": "Once upon a time, in a digital realm, there was a curious chatbot who loved to learn from every conversation...",
	"are you human": "No, I am a computer program. \n\n \u{1F616} \u{1F62D}", 
	"non veg joke": "A couple is on their first date. The man, trying to impress her, says, I'm a very successful businessman. I own a chain of high-end seafood restaurants. \n\nShe smiles and replies, Oh, that's  wonderful! I love seafood. I bet you are great at shucking oysters. \n\nHe winks and says, Let's just say I have never had a complaint. \u{1F60F}",
    "what is a paradox": "A paradox is a statement that, despite sound reasoning from acceptable premises, leads to a conclusion that seems senseless, logically unacceptable, or self-contradictory.",
	"ok": "Hmm..",
	"okay": "Hmm..",
	"hello": "Hello there! How can I help you today?",
    "hi": "Hi there! What can I do for you?"	
    
	};